### ISSUE TITLE
Has compatibility been tested with Spring Boot 3?

### ISSUE THREAD

**Issue by beirtipol** [esanchezros/quickfixj-spring-boot-starter#101]
I'm in the process of upgrading our project to Spring Boot 3 and hit an autowiring error

`required a bean of type 'quickfix.Connector' that could not be found.`

I spotted that this project is built of Spring Boot 2 so I'll dig in to our code and config before raising an actual issue here, but wanted to check if there are plans to rebase on Spring Boot 3 in the near future?

**Comment by esanchezros** [comment]
Hey @beirtipol, thanks for reporting. I'm aware of the issue and working on a new release that should fix it.

**Comment by beirtipol** [comment]
Ah ok, good to know thanks. I'll hold off on my investigation for now.

**Comment by esanchezros** [comment]
Hi @beirtipol,

I just released 2.15.0 of the spring boot starter. Could you give it a go and confirm it works in Spring 3? Also, please let me know if you find any issues.

Thanks

**Comment by beirtipol** [comment]
Amazing, thanks! Just fighting with the cache on our internal nexus to pick up the latest version from maven central. Will test it out and get back to you asap.

**Comment by beirtipol** [comment]
Hmm, it's erroring on a transitive dependency. I can't find the pom for 'quickfixj-spring-boot-dependencies' published on maven central:

`Failed to read artifact descriptor for io.allune:quickfixj-spring-boot-actuator:jar:2.15.0: Could not find artifact io.allune:quickfixj-spring-boot-dependencies:pom:2.15.0`

It looks like you may have changed your parent pom to use the below now but perhaps didn't publish it?

		```
	                <dependency>
				<groupId>io.allune</groupId>
				<artifactId>quickfixj-spring-boot-dependencies</artifactId>
				<version>${project.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
```

**Comment by beirtipol** [comment]
Cloning the repo and building locally sorts the above, however I'm still unfortunately suffering from missing beans in my regression test (at least it's a different bean, so progress is being made!)

`No qualifying bean of type 'quickfix.SessionScheduleFactory`

**Comment by esanchezros** [comment]
Are you trying to configure an initiator or an acceptor? What version of Spring are you using?

Could you provide with an example project or the configuration that you're using? 

There seems to be an issue with Maven Central as I can't see the new version in there. Will look into it.

**Comment by beirtipol** [comment]
Attempting to configure an acceptor session. I'll have to create a sample project with it and get back to you

**Comment by beirtipol** [comment]
Confirmed that 2.15.2 is now working correctly with Spring Boot 3.0.2 and that all dependencies are resolving from maven central. Thank you for the quick turnaround!
