### ISSUE TITLE
@AutoConfiguration annotation compatible

### ISSUE THREAD

**Issue by ChildrenGreens** [esanchezros/quickfixj-spring-boot-starter#105]
Regarding whether the @AutoConfiguration annotation in the QuickFixJClientAutoConfiguration class can be compatible. 

Since I use a lower version of Spring Boot 2.5.8, there is no @AutoConfiguration annotation, so the "clientInitiator" bean cannot be loaded.
 
There is no need to use the @AutoConfiguration annotation for this project, @Configuration is enough

**Comment by esanchezros** [comment]
btw, OSS support for Spring Boot 2.5.8 was ended in May last year, although commercial support is still going for a bit longer. You should at least consider upgrading to [2.5.14](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot/2.5.14) which will contain fixes to a few bugs.

**Comment by esanchezros** [comment]
Hi @ChildrenGreens, I just released version 2.15.3, which gets rid of `@AutoConfiguration` annotation. Please let me know if this version works for you.
Thanks

**Comment by ChildrenGreens** [comment]
@esanchezros Thank you for your suggestion on upgrading to Spring Boot 2.5.13. I will look at the source code and tags later and make an evaluation.

**Comment by esanchezros** [comment]
Closing for now, @ChildrenGreens please feel free to reopen if necessary.
