### ISSUE TITLE
How  to get control over which messages get logged?

### ISSUE THREAD

**Issue by apupneja** [esanchezros/quickfixj-spring-boot-starter#108]
Hi,

In my setup, I have set up the file log option for both the client and the server. Now, the messages start getting logged automatically(it seems to be storing the outgoing messages automatically). How do I get a control over which messages gets logged in the file store, or create a different store?

**Comment by esanchezros** [comment]
This is something that can be controlled in the config file. https://quickfixj.org/usermanual/2.3.0/usage/configuration.html#Logging
The starter makes use of quickfixj as is, so you should be able to customize it using the standard settings
