### ISSUE TITLE
Separate message cracker for separate session

### ISSUE THREAD

**Issue by chusri** [esanchezros/quickfixj-spring-boot-starter#113]
Hi @esanchezros,

May I ask, is it possible to separate the message cracker class for difference session, lets say i have one session for quote and another one for trade. So i need one message cracker to take responsibility to extract data for quote session only, and another class for trade data. if it's possible, could you please suggest how to do it?

Thanks
Chusri

**Comment by esanchezros** [comment]
Hi @chusri,

The MessageCracker is just a helper class that calls the specific onMessage callback depending on the message type. It's typically used in the Application fromApp method to process the message but you can have your own implementation and depending on the session (quote or order management) call one handler or another. Alternatively you can have different applications completely separate, one for handling quote sessions only and another for handling order management only.
