### ISSUE TITLE
After Accept Login

### ISSUE THREAD

**Issue by datdv1** [esanchezros/quickfixj-spring-boot-starter#114]
Hi QuickfixJ Team!
I'm using quickfixj-spring-boot-starter version 2.15.3 on my spring boot application.
Currently, After that login and received message Accept Login, I'm seeing My Application automation send message ResetSequence. Is this an issue?

Maybe my development direction is wrong.
Can you suggest to me best practive development QuickfixJ in spring boot application?

**Comment by esanchezros** [comment]
Hi @datdv1,

Thanks for using the spring boot starter. This is just a spring wrapper around the quickfixj open source library that takes care of many aspects of the FIX session between acceptor and initiator.

To learn more about how a session is established here is a good starting point https://www.fixtrading.org/standards/fix-session-layer-online/
