### ISSUE TITLE
Quickfixjclient health endpoint leaking secrets

### ISSUE THREAD

**Issue by svabrad** [esanchezros/quickfixj-spring-boot-starter#117]
Hi Eduardo! 

I've noticed health endpoint for quickfixjclient is leaking secrets. Passwords for session and proxy are visible. 
Would it be possible to hide it? Perhaps with option like quickfixj.client.actuator.opaque=true.

Thank you for all the great work you are doing, I greatly appreciate it.

**Comment by esanchezros** [comment]
Hey @svabrad, Thanks for reporting, it's a good spot. I'm going to try fixing it in the next few days but please feel free to add a PR if you would like to contribute.
Thanks

**Comment by svabrad** [comment]
Absolutely, I will try to find spare minute.
