### ISSUE TITLE
@EnableQuickFixJClient has been deprecated 

### ISSUE THREAD

**Issue by DUZHANGYI** [esanchezros/quickfixj-spring-boot-starter#119]
Hello @esanchezros  
I saw that @EnableQuickFixJClient has been deprecated in the latest version. I want to know how to open a client in the new version.

**Comment by esanchezros** [comment]
This can be done by defining `quickfixj.server.enabled` property set to `true`

https://github.com/esanchezros/quickfixj-spring-boot-starter#enabling-quickfixj-server-through-a-property
