### ISSUE TITLE
New Release =D

### ISSUE THREAD

**Issue by mballoni** [esanchezros/quickfixj-spring-boot-starter#12]
Hi ESanchez,

 When are you planning on making a new release? (for spring boot 2 with the last PR`s merged)
 I'm migration an application currently using vanilla java to Spring Boot and this starter fits perfectly (good job =D ).

 Speaking about it, is there any todo list that you wanna share? I might help improve this starter.

 Thank you!

**Comment by esanchezros** [comment]
I will try to release it today or tomorrow. 
For the things to do I will gather a list and will share but the main areas to improve are:
- Provide a mechanism to register event listeners for the MessgeCracker through annotations, provide default listener beans that can be extended- Improve health endpoints information - Improve documentation - Create more example apps - Create configurable mock acceptor- Create configurable mock initiator - Create starters for different message stores with the required dependencies ... 
Thanks for your help MarceloRegards, Eduardo 
Sent from Yahoo Mail on Android 
 
  On Wed, 24 Oct 2018 at 23:39, Marcelo Balloni<notifications@github.com> wrote:   
Hi ESanchez,

When are you planning on making a new release? (for spring boot 2 with the last PR`s merged)
I'm migration an application currently using vanilla java to Spring Boot and this starter fits perfectly (good job =D ).

Speaking about it, is there any todo list that you wanna share? I might help improve this starter.

Thank you!

**Comment by mballoni** [comment]
Great, thank you!!
 Gonna work with these todos.

**Comment by esanchezros** [comment]
I think `2.0.x` should now be `master`, I will add another TODO in the list to move `master` into a 1.x branch

**Comment by esanchezros** [comment]
Hi Marcelo, I'm going to make the 2.0.x branch into master, please let me know if you want me to hold for a bit longer.

**Comment by mballoni** [comment]
Absolutely, no need to hold =D

**Comment by esanchezros** [comment]
Done
