### ISSUE TITLE
How to add Custom Tag definition?

### ISSUE THREAD

**Issue by nurrony** [esanchezros/quickfixj-spring-boot-starter#120]
First of all thanks a lot for creating this project. It does most of heavy lifting of the configuration binding. I am just wondering how to add new Custom Tag? Could you please give me some direction. I am using `FIXT 1.1` and `FIX5.0` version 

Thanks in advance

**Comment by esanchezros** [comment]
Hey @nurrony, thank you for using the library. 

About your question, do you mean adding, for example, tag ExampleTag with number 123456 in FIX5.0SP2?

**Comment by nurrony** [comment]
I should have added the information I am trying to add Custom Tag for FIX5.0 using FIXT.1.1

**Comment by esanchezros** [comment]
@nurrony, adding a custom tag for FIX 5.0 has to be done in the quickfixj library. There are a few stackoverflow.com entries on how to do this. Basically you need to add the new tag in the data dictionary in quickfixj and recopile the library. Here is a link on how to change the order of tags but it has a link to the build instructions 

https://stackoverflow.com/questions/60037526/how-to-send-a-fix-message-with-custom-tag-ordering
