### ISSUE TITLE
quickfixj-spring-boot-starter not working with spring-boot 3.2.0 (only works up-to version 3.1.5)

### ISSUE THREAD

**Issue by ntjp** [esanchezros/quickfixj-spring-boot-starter#121]
Steps to reproduce issue:
1) in [quickfixj-spring-boot-starter-examples](https://github.com/esanchezros/quickfixj-spring-boot-starter-examples) pom.xml file, change "spring-boot-dependencies" to 3.2.0
2) Launch "Simple Client and Server using Config String" module.
Note: things work fine up-to version version 3.1.5

Error message:
Parameter 0 of method serverAcceptor in io.allune.quickfixj.spring.boot.starter.configuration.server.QuickFixJServerConfiguration$SocketAcceptorConfiguration required a single bean, but 2 were found:
	- serverApplication: defined by method 'serverApplication' in io.allune.quickfixj.spring.boot.starter.configuration.server.QuickFixJServerConfiguration
	- clientApplication: defined by method 'clientApplication' in io.allune.quickfixj.spring.boot.starter.configuration.client.QuickFixJClientConfiguration

**Comment by esanchezros** [comment]
Hey @ntjp, 

Thanks for using the library and for reporting this issue. It seems that `The version of Spring Framework used by Spring Boot 3.2 no longer attempts to deduce parameter names by parsing bytecode`

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#parameter-name-discovery
https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#parameter-name-retention

I recompiled the quickfixj spring boot starter providing the compilation option `-parameters` and this seems to resolve this issue. Let me have a proper read to the release notes for this spring boot release and will create a new version soon.

Thanks

**Comment by ntjp** [comment]
Thanks a lot for the fix ! 
confirmed to now work fine with spring-boot 3.2.0
Best Regards
