### ISSUE TITLE
Encountered an issue where the server setting code is ambiguous and the manual link provided in the README is outdated.

### ISSUE THREAD

**Issue by ChoiJunsik** [esanchezros/quickfixj-spring-boot-starter#122]
Hi, esanchezros !
I'm now running a service using your great open source

I'd like to contribute to a few things below, and curious about your opinion

### Expected Changes
<img width="753" alt="image" src="https://github.com/esanchezros/quickfixj-spring-boot-starter/assets/26922008/39f5ccac-ad74-4a1b-a9fa-fa7183c312ef">

<img width="805" alt="image" src="https://github.com/esanchezros/quickfixj-spring-boot-starter/assets/26922008/970a8527-f4c4-4af8-93b8-f271fde6f317">

- Update the server setting code to be more explicit and clear. 
- Replace the old manual link in the README with the updated version.

This is my PR Link, Thank you!

https://github.com/esanchezros/quickfixj-spring-boot-starter/pull/123

**Comment by esanchezros** [comment]
Hi @ChoiJunsik, many thanks for using the library. The PR has been merged
