### ISSUE TITLE
Regarding JdbcStore managing two sequences in a single record.

### ISSUE THREAD

**Issue by ydh6226** [esanchezros/quickfixj-spring-boot-starter#124]
Hello,

I'm curious about the JdbcStore logic to store the incoming_seqnum and outgoing_seqnum in the same record of the session table.

Since both the incoming and outgoing processes are trying to update the same record, this approach seems to induce a potential race condition and low throughput. 

In contrast, FireStore keeps these sequences in separate files. 

Is there a specific reason why JdbcStore does not follow a similar approach by keeping the two sequences in separate records? 

Are there any advantages to the current logic that I am not aware of?

Thanks for your time and consideration.

**Comment by esanchezros** [comment]
Hi @ydh6226,

QuickfixJ Spring Boot Starter is just a wrapper around [QuickfixJ](https://github.com/quickfix-j/quickfixj). It simplifies the configuration required to create and start an [Initiator](https://www.quickfixj.org/javadoc/2.3.0/quickfix/Initiator.html) or [Acceptor](https://www.quickfixj.org/javadoc/2.3.0/quickfix/Acceptor.html) and handles the lifecycle of the [Connector](https://www.quickfixj.org/javadoc/2.3.0/quickfix/Connector.html).

With regards to the JdbcStore, this is a class from QuickfixJ but if you look at the implementation you will see that both the `incoming_seqnum` and `outgoing_seqnum` are inserted, updated, and queried at the same time:

https://github.com/quickfix-j/quickfixj/blob/50d004661424eb3d1d07fe78a90cb91d85946c29/quickfixj-core/src/main/java/quickfix/JdbcStore.java#L93 

If you want to know more details of the motivations for such an approach please feel free to raise the question in their repository.

**Comment by ydh6226** [comment]
I was mistaken. Thanks
