### ISSUE TITLE
Quickfixj messages dependencies added by default

### ISSUE THREAD

**Issue by Svanar** [esanchezros/quickfixj-spring-boot-starter#131]
Hi,
I started using your starter and I'm having a blast. However I have one question and would love your feedback on it. What do you think about removing `quickfixj-messages-all` dependency and adding section in README that it should be added like quickfix-j is doing https://github.com/quickfix-j/quickfixj?tab=readme-ov-file#quickfixj-runtime. 
The reason I'm thinking of removing it is that it adds a lot of duplicated classes by default and, for example, in my case we are using only 4.4 version, so I'm not interested in any other classes.

While this is not really an issue, I think that removing of those dependencies would make writing code a bit simpler, because one does not have to scroll through imports to check what exactly is used, IDE will index and search faster.

Looking forward to your feedback.
Thanks!

**Comment by esanchezros** [comment]
Hi @Svanar, 
Thanks for using the starter and for your suggestion. The initial idea of the starter was to reduce the boilerplate configuration needed to start an initiator and an acceptor, but also include all the required dependencies required by quickfixj. 

I understand your point and perhaps a different approach would be to add each library with the specific version to the starter's dependency management with scope `optional` and then allow the user to pick the specific dependency(ies) they want to use.

**Comment by Svanar** [comment]
Thank you for your response. I think that adding `optional ` would resolve all inconveniences I mentioned.
I know that it is possible to exclude some packages from my app pom, but making it not added in the first place would be really really nice in my opinion.

**Comment by esanchezros** [comment]
@Svanar would you mind having a look at this PR https://github.com/esanchezros/quickfixj-spring-boot-starter/pull/133?

**Comment by Svanar** [comment]
@esanchezros I checked and I think that it is exactly what I was thinking about. Thank you :)
Just a though - maybe you should add something to readme that end user should include version that will be used?

**Comment by esanchezros** [comment]
Yes, working on that at the moment. It's a breaking change too so I need to bump the minor version too

**Comment by esanchezros** [comment]
@Svanar I've added a section to the readme explaining the change and will add the breaking change in the release notes. Will you be able to review again and approve the PR please? Thanks

**Comment by esanchezros** [comment]
Available from version 2.18.0

**Comment by Svanar** [comment]
@esanchezros Appologies, I was away from my computer for couple of days and just got back to it. I must say that I really like the change and appreciate your work.
Huge thank you

**Comment by esanchezros** [comment]
No worries @Svanar, let me know if you find any issues with the new version
