### ISSUE TITLE
Disable some logs

### ISSUE THREAD

**Issue by sangduongvan** [esanchezros/quickfixj-spring-boot-starter#23]
Hi Esanchezros,

When I start FIX server I got so much log like that
2019-04-04 11:05:47.333  INFO 3615 --- [ NioProcessor-2] q.mina.acceptor.AcceptorIoHandler        : MINA session created: local=/127.0.0.1:9878, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/127.0.0.1:54468
<20190404-04:05:48, FIX.4.2:EXEC->BANZAI, incoming> (8=FIX.4.29=6535=A34=149=BANZAI52=20190404-04:05:48.29956=EXEC98=0108=3010=230)
<20190404-04:05:48, FIX.4.2:EXEC->BANZAI, event> (Accepting session FIX.4.2:EXEC->BANZAI from /127.0.0.1:54468)
<20190404-04:05:48, FIX.4.2:EXEC->BANZAI, event> (Acceptor heartbeat set to 30 seconds)

It seems logs from lib, how could I disable it, could not follow up the application with that logs.
Thanks

**Comment by esanchezros** [comment]
Hi sangduongvan, 
I agree, quickfixj lib is very verbose. Let me have a look. 
Regards,Eduardo
    En jueves, 4 de abril de 2019 5:10:26 GMT+1, sangduongvan <notifications@github.com> escribió:  
 
 
Hi Esanchezros,

When I start FIX server I got so much log like that
2019-04-04 11:05:47.333 INFO 3615 --- [ NioProcessor-2] q.mina.acceptor.AcceptorIoHandler : MINA session created: local=/127.0.0.1:9878, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/127.0.0.1:54468
<20190404-04:05:48, FIX.4.2:EXEC->BANZAI, incoming> (8=FIX.4.29=6535=A34=149=BANZAI52=20190404-04:05:48.29956=EXEC98=0108=3010=230)
<20190404-04:05:48, FIX.4.2:EXEC->BANZAI, event> (Accepting session FIX.4.2:EXEC->BANZAI from /127.0.0.1:54468)
<20190404-04:05:48, FIX.4.2:EXEC->BANZAI, event> (Acceptor heartbeat set to 30 seconds)

It seems logs from lib, how could I disable it, could not follow up the application with that logs.
Thanks

**Comment by esanchezros** [comment]
Hi sangduongvan, 

I changed default `LogFactory` to create a `ScreenLogFactory` using the `SessionSettings`. Now you should be able to control quickfixj core logging by setting these flags in either `quickfixj-server.cfg` or `quickfixj-client.cfg`:

```
ScreenLogShowEvents=Y
ScreenLogShowIncoming=Y
ScreenLogShowOutgoing=Y
ScreenLogShowHeartBeats=Y
```

I will release a new version shortly with this change.

**Comment by esanchezros** [comment]
Hi sangduongvan,

Just released 2.4.1. Please let me know if you are happy with it and I will close this issue.

Regards,
Eduardo

**Comment by sangduongvan** [comment]
Hi Eduardo,
I tried by cannot get version 2.4.1 from maven repo, It's not available yet.
https://mvnrepository.com/artifact/io.allune/quickfixj-spring-boot-starter

**Comment by esanchezros** [comment]
Hi sangduongvan,

Apologies, the release didn't go through. I just fixed it and should be available in Maven Central.

Regards,
Ed

**Comment by sangduongvan** [comment]
I checked, all good, thank you very much
