### ISSUE TITLE
Log quickfix events to file

### ISSUE THREAD

**Issue by JELugoM** [esanchezros/quickfixj-spring-boot-starter#26]
Hi, your library is awesom but i need some help, how can I log to a file the quickfix events, I'm already set in my properties 'logging.file=app.log' but in the file is only the logs for info, debug etc but a need the logs from quickfix, somthing like this:

<20190713-19:33:36, FIX.4.1:BANZAI->EXEC, error> (java.net.ConnectException during connection to localhost/127.0.0.1:9877: java.net.ConnectException: Connection refused: no further information (Next retry in 5000 milliseconds))

I think that this log is not in the file because it is not a info, or debug, but i need to save this logs in the file, can you help me, thanks.

**Comment by esanchezros** [comment]
Hi JELugoM,

Could you send your configuration file please? 

Thanks

**Comment by esanchezros** [comment]
Hi JELugoM,

**quickfixj-spring-boot-starter** configures by default a **ScreenLogFactory** bean. If you want you can override it with a **FileLogFactory**. For example, in the client application you can declare this bean:

    @Bean
    public LogFactory clientLogFactory(SessionSettings clientSessionSettings) {
        return new FileLogFactory(clientSessionSettings);
    }

And in the **quickfixj-client.cfg** configuring file, specify where the log path:

    FileLogPath=logs-client

Here is an example of the log4j.properties I've used to configure the events and messages log files for all the sessions:

```
#
# Loggers
#

# Catch-all
log4j.rootLogger=INFO, ROOT

# Repeat for each session...

log4j.logger.EXEC.BANZAI=INFO, EXEC_BANZAI
log4j.additivity.EXEC.BANZAI=false
log4j.logger.EXEC.BANZAI.events=INFO, EXEC_BANZAI_EV
log4j.additivity.EXEC.BANZAI.events=false

#
# Appenders
#

log4j.appender.ROOT=org.apache.log4j.RollingFileAppender
log4j.appender.ROOT.File=log/QuickFixJ-root.log
log4j.appender.ROOT.layout=org.apache.log4j.PatternLayout
log4j.appender.ROOT.layout.ConversionPattern=%d{DATE} %p [%t] %c - %m %n
log4j.appender.ROOT.MaxFileSize=500KB
log4j.appender.ROOT.MaxBackupIndex=3

# Repeat for each session...

log4j.appender.EXEC_BANZAI=org.apache.log4j.DailyRollingFileAppender
log4j.appender.EXEC_BANZAI.DatePattern='.'yyyy-MM-dd
log4j.appender.EXEC_BANZAI.File=log/EXEC-BANZAI.messages.log
log4j.appender.EXEC_BANZAI.layout=org.apache.log4j.PatternLayout
log4j.appender.EXEC_BANZAI.layout.ConversionPattern=%m%n

log4j.appender.EXEC_BANZAI_EV=org.apache.log4j.DailyRollingFileAppender
log4j.appender.EXEC_BANZAI_EV.DatePattern='.'yyyy-MM-dd
log4j.appender.EXEC_BANZAI_EV.File=log/EXEC-BANZAI.events.log
log4j.appender.EXEC_BANZAI_EV.layout=org.apache.log4j.PatternLayout
log4j.appender.EXEC_BANZAI_EV.layout.ConversionPattern=%d{DATE}: %m%n
```

So now you should have a **messages** and **events** file per session. 

I.e. **FIX.4.0-BANZAI-EXEC.messages.log**:

```
8=FIX.4.09=6135=A34=149=BANZAI52=20190714-14:08:4556=EXEC98=0108=3010=019
8=FIX.4.09=6135=A34=149=EXEC52=20190714-14:08:4556=BANZAI98=0108=3010=019
8=FIX.4.09=4935=034=249=EXEC52=20190714-14:09:1656=BANZAI10=239
8=FIX.4.09=4935=034=249=BANZAI52=20190714-14:09:1656=EXEC10=239
8=FIX.4.09=4935=534=349=EXEC52=20190714-14:09:2756=BANZAI10=247
8=FIX.4.09=4935=534=349=BANZAI52=20190714-14:09:2756=EXEC10=247
```

**FIX.4.0-BANZAI-EXEC.event.log**

```
20190714-14:08:44: Session FIX.4.0:BANZAI->EXEC schedule is daily, 00:00:00-UTC - 00:00:00-UTC
20190714-14:08:44: Created session: FIX.4.0:BANZAI->EXEC
20190714-14:08:44: Configured socket addresses for session: [localhost/127.0.0.1:9876]
20190714-14:08:44: MINA session created: local=/127.0.0.1:36482, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=localhost/127.0.0.1:9876
20190714-14:08:45: Initiated logon request
20190714-14:08:45: Received logon
20190714-14:09:27: Received logout request
20190714-14:09:27: Sent logout response
20190714-14:09:27: Disconnecting: Received logout request
20190714-14:09:27: java.net.ConnectException during connection to localhost/127.0.0.1:9876: java.net.ConnectException: Connection refused (Next retry in 5000 milliseconds)
20190714-14:09:32: java.net.ConnectException during connection to localhost/127.0.0.1:9876: java.net.ConnectException: Connection refused (Next retry in 5000 milliseconds)
```

You can apply the same for the server application, naming your LogFactory bean as **serverLogFactory**.
