### ISSUE TITLE
On starting client and server fromApp and toApp method is not getting invoked

### ISSUE THREAD

**Issue by barunindia1** [esanchezros/quickfixj-spring-boot-starter#27]
On starting client and server fromApp and toApp method is not getting invoked

**Comment by barunindia1** [comment]
Could you plz assist on this?

**Comment by barunindia1** [comment]
Hi Esanchezros,
On running client and server both. What I found is, only onCreat, fromAdmin, toAdmin and logon method is getting involved and logger is logging logged to the console but  neither fromApp nor  toApp method logger logging. 
In fact both is not getting involved. 

Is there any configuration is there? So that after such configuration fromApp method would get called.

I am new to the quickfixj, so just wanted to know when fromApp method and toApp method will get called. I know from quickfixj document. Both method will get call when there is application message. 
If you could provide example with client sending some order message to the server and server revert back with appropriate response, would be great. 
Thanks, 
Barun

**Comment by esanchezros** [comment]
Hi Barun,

From [quickfix](http://www.quickfixengine.org/quickfix/doc/html/application.html) engine docs:

`fromApp` receives application level request. If your application is a sell-side OMS, this is where you will get your new order requests. If you were a buy side, you would get your execution reports here.

`toApp` is a callback for application messages that are being sent to a counterparty.

So if you are the client and want to send a message to the server you can do something like this:

	@Autowired
	private ThreadedSocketInitiator clientInitiator;

	@Test
	public void sendToTarget() throws Exception {
		quickfix.fix41.OrderCancelRequest message = new quickfix.fix41.OrderCancelRequest(
				new OrigClOrdID("123"),
				new ClOrdID("321"),
				new Symbol("LNUX"),
				new Side(Side.BUY));

		message.set(new Text("Cancel My Order!"));

                // Here, get the session you want to send the message to, for illustration purposes I'm getting the first one available
		Session session = clientInitiator.getManagedSessions().get(0);
		session.send(message);
	}

You can see the whole example [here](https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/issues/4)

**Comment by esanchezros** [comment]
Closing as not an issue
