### ISSUE TITLE
MessageCracker

### ISSUE THREAD

**Issue by Romanroad6** [esanchezros/quickfixj-spring-boot-starter#31]
Do you handle the logic in the fromApp() and fromAdmin()?
I overrided the onMessage() of the MessageCracker class to handle the logic.
I want to konw how I can handle the logic with this quickfixj-spring-boot-starter.
Thanks.

**Comment by esanchezros** [comment]
Hi,

You can implement your `MessageCracker` and inject it into the `Application` bean.

```
public class ApplicationMessageCracker extends MessageCracker {

    @Override
    public void onMessage(OrderCancelRequest message, SessionID sessionID)
            throws FieldNotFound, UnsupportedMessageType, IncorrectTagValue {

        // Handle the message here

    }
}
```

```   
@Bean
public Application clientApplication(MessageCracker messageCracker) {
    return new ClientApplicationAdapter(messageCracker);
}

@Bean
public MessageCracker messageCracker() {
    return new ApplicationMessageCracker();
}
```

And then in your `Application` call the `crack` method in the `fromApp` 

```
@Override
public void fromAdmin(Message message, SessionID sessionId) {
	log.info("fromAdmin: Message={}, SessionId={}", message, sessionId);
	try {
		messageCracker.crack(message, sessionId);
	} catch (UnsupportedMessageType | FieldNotFound | IncorrectTagValue e) {
		log.error(e.getMessage(), e);
	}
}
```

**Comment by Romanroad6** [comment]
Thanks! I'll try it.

**Comment by esanchezros** [comment]
Cool, let me know if you need anything else

**Comment by robertfernanV** [comment]
Hi! if i extends from MessageCracker in  Application on implementes  onMessage 
it should work? i try but dont work

**Comment by esanchezros** [comment]
Hi,

I just added an example on how to use the `MessageCracker` in the examples project https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client/src/main/java/io/allune/quickfixj/spring/boot/starter/examples/client

Let me know if that's what you're looking for

**Comment by robertfernanV** [comment]
Hello thanks for the example! It helped me a lot!
