### ISSUE TITLE
Multi quickfix client for different users

### ISSUE THREAD

**Issue by duongvansang** [esanchezros/quickfixj-spring-boot-starter#32]
Hi @esanchezros,

Could you tell me how can I configure for multi quickfix clients in the same app?

For example, I have a app that need to connect to multi quickfix servers
Quickfix server 1: IP1, port1, user1
Quickfix server 2: IP2, port 2, user2

Many thanks,

**Comment by esanchezros** [comment]
Hi @duongvansang,

You can create multiple sessions pointing to different hosts in the quickfix config:

`# default settings for sessions
[default]
ConnectionType=initiator
ReconnectInterval=60
SenderCompID=TW

# session definition
[session]
# inherit ConnectionType, ReconnectInterval and SenderCompID from default
BeginString=FIX.4.1
TargetCompID=ARCA
StartTime=12:30:00
EndTime=23:30:00
HeartBtInt=20
SocketConnectPort=9823
SocketConnectHost=123.123.123.123
DataDictionary=somewhere/FIX41.xml

[session]
BeginString=FIX.4.0
TargetCompID=ISLD
StartTime=12:00:00
EndTime=23:00:00
HeartBtInt=30
SocketConnectPort=8323
SocketConnectHost=23.23.23.23
DataDictionary=somewhere/FIX40.xml

[session]
BeginString=FIX.4.2
TargetCompID=INCA
StartTime=12:30:00
EndTime=21:30:00
# overide default setting for RecconnectInterval
ReconnectInterval=30
HeartBtInt=30
SocketConnectPort=6523
SocketConnectHost=3.3.3.3
# (optional) alternate connection ports and hosts to cycle through on failover
SocketConnectPort1=8392
SocketConnectHost1=8.8.8.8
SocketConnectPort2=2932
SocketConnectHost2=12.12.12.12
DataDictionary=somewhere/FIX42.xml`

* Example taken from http://www.quickfixengine.org/quickfix/doc/html/configuration.html

**Comment by duongvansang** [comment]
Hi @esanchezros,

yes, I tried, it's good now thank you very much
I am trying to run both FIX server and FIX client in the same app, but I got error could not do it

Is there any way to config to run both FIX Server and FIX client in the same app?

**Comment by esanchezros** [comment]
Yes it's possible. What error are you getting? 

Sent from Yahoo Mail on Android 
 
  On Wed, 19 Feb 2020 at 8:41, duongvansang<notifications@github.com> wrote:   
Hi @esanchezros,

yes, I tried, it's good now thank you very much
I am trying to run both FIX server and FIX client in the same app, but I got error could not do it

Is there any way to config to run both FIX Server and FIX client in the same app?

**Comment by duongvansang** [comment]
I got this error when enable both Server and client in the same app
 Error creating bean with name 'clientInitiator' defined in class path resource [config/FIXInitiatorConfig.class]: Unsatisfied dependency expressed through method 'clientInitiator' parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientLogFactory' defined in class path resource [io/allune/quickfixj/spring/boot/starter/autoconfigure/client/QuickFixJClientAutoConfiguration.class]: Unsatisfied dependency expressed through method 'clientLogFactory' parameter 0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'quickfix.SessionSettings' available: expected single matching bean but found 2: clientSessionSettings,serverSessionSettings

It seems there is two beans of quickfix.SessionSettings type are available.

**Comment by esanchezros** [comment]
What version are you using? I think I fixed this issue on the latest one (2.5.0)

Sent from Yahoo Mail on Android 
 
  On Wed, 19 Feb 2020 at 8:58, duongvansang<notifications@github.com> wrote:   
I got this error when enable both Server and client in the same app
Error creating bean with name 'clientInitiator' defined in class path resource [config/FIXInitiatorConfig.class]: Unsatisfied dependency expressed through method 'clientInitiator' parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientLogFactory' defined in class path resource [io/allune/quickfixj/spring/boot/starter/autoconfigure/client/QuickFixJClientAutoConfiguration.class]: Unsatisfied dependency expressed through method 'clientLogFactory' parameter 0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'quickfix.SessionSettings' available: expected single matching bean but found 2: clientSessionSettings,serverSessionSettings

It seems there is two beans of quickfix.SessionSettings type are available.

**Comment by duongvansang** [comment]
oh I am using 2.4.1, let me try 2.5.0

**Comment by duongvansang** [comment]
I tried, it works now, great
Thank you

**Comment by esanchezros** [comment]
That's great. From now on I will publish release notes with new changes/bug fixes. 

Sent from Yahoo Mail on Android 
 
  On Wed, 19 Feb 2020 at 9:05, duongvansang<notifications@github.com> wrote:   
I tried, it works now, great
Thank you
