### ISSUE TITLE
Could not accept connection when run both FIX server and FIX client

### ISSUE THREAD

**Issue by duongvansang** [esanchezros/quickfixj-spring-boot-starter#33]
Hi @esanchezros,

When I run both FIX Client and FIX Server in the same app,

And whenever FIX client connection is not connected yet, FIXServer will never accept any request from client.

It should be separated thread, FIX Server does it job and FIX client does it own job.
Thanks
Sang.

**Comment by esanchezros** [comment]
Hi Sang,
Could you confirm what version you're using?
Thanks

**Comment by duongvansang** [comment]
I am using latest one I think, version 2.5.0

**Comment by esanchezros** [comment]
I just created an example project that uses client and server. It seems to be working okay

https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/add-client-and-sender-example/simple-client-and-server

Could you share your project so I can have a look?

**Comment by duongvansang** [comment]
Thanks you
little bit busy these days, I will try your sample and let you know about it

**Comment by esanchezros** [comment]
@duongvansang did you have the chance to test the sample project I added?

The spring boot starter creates separate beans for client and server, which instantiate separate instances for the `Initiator` and `Acceptor`. Both client and server should work together okay on the same application.
