### ISSUE TITLE
How add custom quickfix engine!

### ISSUE THREAD

**Issue by robertfernanV** [esanchezros/quickfixj-spring-boot-starter#35]
Hi, I find myself needing to add a custom version of quickfix to support my custom messages.
What would be the procedure to add this version of quickfix to this project?

**Comment by esanchezros** [comment]
Hi Roberto,

You can exclude the version of `quickfixj-core` and `quickfixj-messages-all` from `quickfixj-spring-boot-starter` (and `quickfixj-spring-boot-actuator` if you use it) and include your custom version:

	<dependency>
		<groupId>io.allune</groupId>
		<artifactId>quickfixj-spring-boot-starter</artifactId>
		<exclusions>
			<exclusion>
				<groupId>org.quickfixj</groupId>
				<artifactId>quickfixj-core</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.quickfixj</groupId>
				<artifactId>quickfixj-messages-all</artifactId>
			</exclusion>
		</exclusions>
	</dependency>

	<dependency>
		<groupId>io.allune</groupId>
		<artifactId>quickfixj-spring-boot-actuator</artifactId>
		<exclusions>
			<exclusion>
				<groupId>org.quickfixj</groupId>
				<artifactId>quickfixj-core</artifactId>
			</exclusion>
		</exclusions>
	</dependency>

	<dependency>
		<groupId>org.quickfixj</groupId>
		<artifactId>quickfixj-core</artifactId>
		<version>1.6.2</version>
	</dependency>

	<dependency>
		<groupId>org.quickfixj</groupId>
		<artifactId>quickfixj-messages-all</artifactId>
		<version>1.6.2</version>
	</dependency>

**Comment by esanchezros** [comment]
@robertfernanV, did that work for you?

**Comment by robertfernanV** [comment]
@esanchezros Thanks a lot
