### ISSUE TITLE
Enhancements 

### ISSUE THREAD

**Issue by esanchezros** [esanchezros/quickfixj-spring-boot-starter#37]
Hi,

I was wondering if there are any features or enhancements you would like to see in the quickfixj spring boot starter. I have a few things in mind to improve the library and also wanted to work on making the examples better but I would like to hear from people using the library.

Thanks
Eduardo

**Comment by raph1mm** [comment]
Some integration testing tips and enhancements for apps using this lib would be nice. :)

**Comment by esanchezros** [comment]
That's a good suggestion @raph1mm, I will try adding an example specific to testing with Spring Boot Test.
Thanks

**Comment by peyerroger** [comment]
Hi @esanchezros 

Where would you put these examples? I have a reasonable integration test for an application that acts as initiator. The mock acts as acceptor.  You can configure the mock to send a series of execution reports upon receiving a NewOrderSingle, an OrderCancelRequest or an OrderCancelReplaceRequest with a specific ClOrdId. This way you can easily mock an exchange or a broker.

Cheers,
Roger

**Comment by esanchezros** [comment]
Hi @peyerroger 

Feel free to create a new module in the examples project. Having an integration tests module will be really useful for other users. 

Thanks

**Comment by aniket0788** [comment]
Hi @esanchezros 

I am getting this error when trying to initiate connection

`inbound queue size > upper watermark (-1), socket reads suspended`

because of this acceptor is not receiving any messages (fromApp is not getting called !)

Could you please have a look and fix it? Or, I am missing something where you could help?

**Comment by esanchezros** [comment]
Hi @aniket0788 

Could you please create a separate issue? This thread is to discuss and propose new enhancements for the library

Thanks

**Comment by aniket0788** [comment]
Thanks @esanchezros , I have opened an issue [here](https://github.com/esanchezros/quickfixj-spring-boot-starter/issues/45)
