### ISSUE TITLE
Error's compile with Spring boot 2.0.3

### ISSUE THREAD

**Issue by max-dicson-cf** [esanchezros/quickfixj-spring-boot-starter#4]
Hello,
I was trying to migrate to the version of Springboot 2 but without success, errors come out in source code.

It would be great if I could migrate.
Thank you

**Comment by esanchezros** [comment]
Hi max,

I just had a look and it seems `ResourceCondition` has been changed. I'll create a branch and push a fix for Spring Boot 2.0.3

**Comment by esanchezros** [comment]
Hi max, 

I have created branch [using-spring-boot-2](https://github.com/esanchezros/quickfixj-spring-boot-starter/tree/using-spring-boot-2) of the project using Spring Boot 2.0.3. Please let me know if this works for you and I will release version 2.0.0 of the project.

Ed

**Comment by max-dicson-cf** [comment]
Thanks So Much...
this Work is great... :)
