### ISSUE TITLE
Empty FileStorePath

### ISSUE THREAD

**Issue by aniket0788** [esanchezros/quickfixj-spring-boot-starter#46]
Hi @esanchezros 

I am getting outOfMemory error in my spring boot application, which reads huge data volume from Kafka Topics and send to FIX Initiator Engine. On analysis I found that, this is because of the internal MessageQueue that QuickFixJ uses to send the gap fills.
To avoid storing it in memory I used FileStoreMaxCachedMsgs=0 (as per quickfixj documentation), but somehow it is not taking effect. FileStorePath is always empty, I never see any files under them.
Not sure what am I missing? Tried both of your examples:
https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client-listener
https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client

FileLogPath is getting created but FileStorePath isn't. Could you please help?

**Comment by esanchezros** [comment]
Hi @aniket0788,

Could you send your quickfixj configuration?

**Comment by aniket0788** [comment]
Please find it below:

```
[DEFAULT]
ConnectionType=initiator
SenderCompID=TEST
TargetCompID=TARGET
ReconnectInterval=10
UseDataDictionary=N
FileStoreMaxCachedMsgs=0
FileStorePath=/pathTo/store
FileLogPath=/pathTo/log

[SESSION]
BeginString=FIX.4.4
HeartBtInt=30
StartTime=00:00:00
EndTime=00:00:00
TimeZone=America/New_York
SocketConnectHost=xyz
SocketConnectPort=9877
ResetOnLogon=Y
SocketUseSSL=Y
CipherSuites=TLS_RSA_WITH_AES_128_CBC_SHA
EnabledProtocols=TLSv1.2
```

**Comment by esanchezros** [comment]
Thanks, could you also send the stacktrace of the exception you're getting?

Also, are you creating a `MessageStoreFactory` bean in your spring boot application of type `FileStoreFactory`? The default one that the spring boot starter creates, if no other is defined, is a `MemoryStoreFactory`.

**Comment by esanchezros** [comment]
Hi @aniket0788 

I have created a `FileStoreFactory` on my test app like this:

	@Bean
	public MessageStoreFactory clientMessageStoreFactory(SessionSettings clientSessionSettings) {
		return new FileStoreFactory(clientSessionSettings);
	}

and I can see the file store files being created in the file system:
 
![image](https://user-images.githubusercontent.com/627002/88657819-c41a7800-d0d2-11ea-9535-c80603719569.png)

Are you still having problems?

**Comment by aniket0788** [comment]
Thanks @esanchezros , Yes I did the same and it works now. 
But I ran into another issue, these files are very huge in mycase (especially .body file) because of the large messages that I am sending (tag 213 -> XmlData) and its occupying GBs on disk within few minutes of app run. 
Is there a way to clear them after sometime or may be some rolling policy?

**Comment by esanchezros** [comment]
Hi @aniket0788,

I checked quickfixj configuration guide and it seems there aren't any options to control the file size or provide with a rolling policy. 

Perhaps you could consider using MySql or Postgres store factories and then have a job that clears out old rows horly, daily, etc
