### ISSUE TITLE
quickfixj-spring-boot-actuator doesn't work

### ISSUE THREAD

**Issue by aniket0788** [esanchezros/quickfixj-spring-boot-starter#49]
Hi @esanchezros 

I have integrated this in my pom.xml as documented by you [here](https://github.com/esanchezros/quickfixj-spring-boot-starter)

```
<dependency>
    <groupId>io.allune</groupId>
    <artifactId>quickfixj-spring-boot-actuator</artifactId>
    <version>2.6.0</version>
</dependency>
```
and
```
management.endpoint.quickfixjclient.enabled=true
management.endpoints.web.exposure.include=quickfixjclient
```

But, its not working and endpoint is not populated. Is something related with the groupId `'org.springframework.boot'` i.e.

```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.2.5.RELEASE</version>
    <relativePath/> 
 </parent>
```

I have seen in your examples, you used:
```
<parent>
        <artifactId>quickfixj-spring-boot-starter-examples</artifactId>
        <groupId>io.allune</groupId>
        <version>2.6.0</version>
</parent>
```

Is there any restrictions in using the actuator? I am developing a related app for my organization and can't use anything other that `boot` as per policies.

**Comment by esanchezros** [comment]
Hi @aniket0788 

Do you see anything in the logs?

**Comment by aniket0788** [comment]
Hi @esanchezros - Got it working after removing spring-boot-starter-actuator from pom.xml. So is `quickfixj-spring-boot-starter ` is a wrapper on top of `spring-boot-starter-actuator`? And by using it would I be able to get all the features of spring-boot-actuator? Please clarify.
Also, is there an endpoint that I can enable to monitor the health or status of running FIX engine?

**Comment by esanchezros** [comment]
Hi @aniket0788,
`quickfixj-spring-boot-actuator` makes use of `spring-boot-starter-actuator`. `quickfixj-spring-boot-starter` doesn't use the actuator. I noticed that `quickfixj-spring-boot-parent` has the actuator on its dependency management section. I need to double check why it's there, I can't think of a reason why it should be, but I wonder if that could be messing with the dependences. Glad it's working

**Comment by aniket0788** [comment]
Sorry @esanchezros, did a typo in my above comment. Wanted to mention `quickfixj-spring-boot-actuator`. Edited it.

**Comment by esanchezros** [comment]
Hi @aniket0788, there is no endpoint to monitor the status of the connections yet. I think it's a good feature to add to the actuator. I will create a new enhancement to include in a future release.

With regards to `quickfixj-spring-boot-actuator` being a wrapper on top of `spring-boot-starter-actuator` I need to have a look at this. It may be that `spring-boot-starter-actuator` is not needed as a dependency.

**Comment by aniket0788** [comment]
Thanks @esanchezros , I will wait for this awesome feature.

**Comment by esanchezros** [comment]
No worries @aniket0788. If you have any suggestions on how to determine the health or status of running FIX engine or want to implement it, you are more than welcome.

**Comment by aniket0788** [comment]
Thanks @esanchezros. Frankly, I just started with FIX protocol/QuickFixJ and understanding its semantics. I don't have any suggestions as of now, on how to determine the status of FIX engine. But surely would let you know if I come across anything.
