### ISSUE TITLE
Dependency convergence Error for mina-core

### ISSUE THREAD

**Issue by aniket0788** [esanchezros/quickfixj-spring-boot-starter#64]
Hi @esanchezros @mballoni @chrjohn @bhanuhiteshi ,

Kudos on your ongoing great work for the community ! Hope you guys are doing great.

Would like to highlight a Dependency Convergence Error which arises when maven enforcer plugin is used.
Actually, mina-core is present as a direct dependency in quickfixj-spring-boot-starter and also inside quickfixj-core.
I believe direct dependency can be removed as its already present in quickfixj-core.
```
<dependency>
  <groupId>org.apache.mina</groupId>
  <artifactId>mina-core</artifactId>
  <version>${mina.version}</version>
</dependency>
```
Could you please have a look?

**Comment by esanchezros** [comment]
Hi @aniket0788,

Thanks for the heads up. I can't remember why it was added in the first place but it's not required as it's pulled transitively from quickfixj-core. I'm a bit swamped with work at the moment but feel free to create a PR to get this fixed.

**Comment by aniket0788** [comment]
Hi @esanchezros created a PR, please have a look.
