### ISSUE TITLE
Request to update lib version in maven repo

### ISSUE THREAD

**Issue by style-x7** [esanchezros/quickfixj-spring-boot-starter#67]
Hi there,

Thanks for the wonderful lib :) The latest commits that you've made, possible to update maven repo which is currently at 2.81

Need the commit/fix to remove the Mina core dependency. And I can only pull via maven repo.

**Comment by esanchezros** [comment]
Hi,

The Mina dependency come transitively from the quickfixj lib, which is used to establish the connection. Could you explain the issue that you're having?

**Comment by esanchezros** [comment]
I will try to release a new version tomorrow morning.

**Comment by esanchezros** [comment]
Sorry for the late response. Maven Central was having issues with staging repositories and wasn't able to release software. Version 2.8.3 is now available

**Comment by style-x7** [comment]
Thanks Sir. The Mina dependency was causing lib conflict with the server hosting this. Though I can resolve with exclusion but 2.8.3 is better :)
