### ISSUE TITLE
config file not work ?

### ISSUE THREAD

**Issue by AntonyM55** [esanchezros/quickfixj-spring-boot-starter#68]
If I change the config path to different file such as /root/quickfixj-client.cfg, it doesn't work. 

quickfixj:
  client:
    config: /root/quickfixj-client.cfg

**Comment by esanchezros** [comment]
Hi @AntonyM55 

The quickfixj Spring Boot starter uses the `PathMatchingResourcePatternResolver`  to load the config file. The configuration is resolved using the following approach: 

- By a configuration file defined by the `quickfixj.server.config` or `quickfixj.client.config` property.
- By the presence of the `quickfixj.server.config` or `quickfixj.server.config` system property.
- By a `quickfixj-server.cfg` or `quickfixj-client.cfg` file in the working directory or at the root of the classpath.

If you want to use a file, you will need to prefix it with `file:`, so in your case `file:/root/quickfixj-client.cfg`

**Comment by AntonyM55** [comment]
Thank you very much!
