### ISSUE TITLE
Missing json conversion

### ISSUE THREAD

**Issue by rajendra1** [esanchezros/quickfixj-spring-boot-starter#73]
Hi, We are integrating our trading platform with Kafka, initially I was looking for Fix transoformation library via Connetor. but that was limiting us .
   Well When I using this library its fabulous to deal with FIX engine, but wondering why we don't 
     message.toJson() methods  similar to message.toXml()
    I can certainly make use of xml to transform in Json but that will add couple of millis in execution's time.
  
    is their any way I can tranform message directly to JSON ? 

linkedin.com/in/rajendra-patil

**Comment by esanchezros** [comment]
Hi Rajendra, perhaps I don't fully understand your question. Do you mean you'd prefer to have a `toJSON` method on the `Message` class? This Spring Boot starter is just a wrapper around
