### ISSUE TITLE
How to prevent automatic logon of Initiator

### ISSUE THREAD

**Issue by miladamery** [esanchezros/quickfixj-spring-boot-starter#92]
Hi. I want to disable automatic logon of Initiator and control it manually. according to this [stackoverflow](https://stackoverflow.com/a/69493831/6574475) link seems that its possible in quickfixj. how can I do it in starter?

**Comment by miladamery** [comment]
Set auto-startup to false

**Comment by esanchezros** [comment]
You can also control the logon action by implementing the `canLogon` method from the application interface
